(ns compiler.core
  (:import com.sun.jna.Pointer)
  (:import com.sun.jna.Function))

(def ^:dynamic *lib* 'LLVM-3.3)

(defn get-function [s]
  `(com.sun.jna.Function/getFunction ~(name *lib*) ~(name s)))

(defmacro defnative [return-type function-symbol]
  `(let [func# ~(get-function function-symbol)]
     (defn ~(symbol (apply str (drop 4 (name function-symbol)))) [& args#]
       (.invoke func# ~return-type (to-array args#)))))

(defnative Pointer LLVMInt1Type)
(defnative Pointer LLVMInt8Type)
(defnative Pointer LLVMInt32Type)
(defnative Pointer LLVMInt64Type)
(defnative Pointer LLVMIntType)
(defnative Pointer LLVMHalfType)
(defnative Pointer LLVMFloatType)
(defnative Pointer LLVMDoubleType)
(defnative Pointer LLVMFunctionType)
(defnative Pointer LLVMStructType)
(defnative Pointer LLVMPointerType)
(defnative Pointer LLVMVoidType)
(defnative Pointer LLVMInt64Type)
(defnative Pointer LLVMArrayType)
(defnative Pointer LLVMVectorType)

(defnative Pointer LLVMModuleCreateWithName)

(defnative Integer LLVMSetFunctionCallConv)
(defnative Integer LLVMFindFunction)
(defnative Pointer LLVMAppendBasicBlock)
(defnative Pointer LLVMCreateBuilder)
(defnative Pointer LLVMGetParam)
(defnative Pointer LLVMAddFunction)
(defnative Integer LLVMPositionBuilderAtEnd)
(defnative Boolean LLVMVerifyModule)
(defnative Pointer LLVMCreateModuleProviderForExistingModule)
(defnative Integer LLVMCreateInterpreterForModule)
(defnative Pointer LLVMCreatePassManager)
(defnative Pointer LLVMGetExecutionEngineTargetData)
(defnative Integer LLVMAddTargetData)
(defnative Integer LLVMRunPassManager)
(defnative Integer LLVMDumpModule)
(defnative Integer LLVMDisposePassManager)
(defnative Integer LLVMDisposeExecutionEngine)
(defnative Integer LLVMBuildRet)
(defnative Integer LLVMBuildRetVoid)
(defnative Integer LLVMLinkInJIT)
(defnative Integer LLVMLinkInInterpreter)
(defnative Integer LLVMInitializeX86Target)
(defnative Integer LLVMInitializeX86TargetInfo)
(defnative Integer LLVMInitializeX86TargetMC)
(defnative Pointer LLVMRunFunction)
(defnative Boolean LLVMFindFunction)
(defnative Pointer LLVMCreateGenericValueOfInt)
(defnative Integer LLVMGenericValueToInt)
(defnative Pointer LLVMBuildAdd)
(defnative Pointer LLVMBuildSub)
(defnative Pointer LLVMConstInt)
(defnative Pointer LLVMConstReal)
(defnative Pointer LLVMBuildICmp)
(defnative Pointer LLVMBuildFCmp)
(defnative Pointer LLVMBuildCondBr)
(defnative Pointer LLVMBuildPhi)
(defnative Integer LLVMAddIncoming)
(defnative Pointer LLVMTypeOf)
(defnative Integer LLVMCountParamTypes)
(defnative Integer LLVMGetTypeKind)
(defnative Integer LLVMDisposeGenericValue)
(defnative Integer LLVMDisposeBuilder)
(defnative Pointer LLVMBuildBr)
(defnative Pointer LLVMBuildCall)
(defnative Pointer LLVMBuildAlloca)
(defnative Pointer LLVMBuildFree)
(defnative Pointer LLVMBuildLoad)
(defnative Pointer LLVMBuildStore)
(defnative Pointer LLVMBuildArrayMalloc)
(defnative Pointer LLVMBuildGEP)
(defnative Pointer LLVMBuildBitCast)
(defnative Pointer LLVMBuildCast)
(defnative Pointer LLVMConstString)
(defnative Pointer LLVMConstInt)
(defnative Integer LLVMCountStructElementTypes)
(defnative Pointer LLVMConstPointerCast)
(defnative Pointer LLVMGetStructElementTypes)
(defnative Integer LLVMGetTypeKind)
(defnative Pointer LLVMConstPointerNull)
(defnative Pointer LLVMDumpValue)
(defnative Integer LLVMGetArrayLength)
(defnative Pointer LLVMGetElementType)
(defnative Pointer LLVMConstArray)
(defnative Pointer LLVMConstString)
(defnative Pointer LLVMConstStruct)
(defnative Pointer LLVMConstGEP)
(defnative Pointer LLVMConstVector)
(defnative Pointer LLVMConstBitCast)
(defnative Integer LLVMCountParams)
(defnative Pointer LLVMAddGlobal)
(defnative Pointer LLVMAddGlobalInAddressSpace)
(defnative Integer LLVMSetInitializer)
(defnative Integer LLVMWriteBitcodeToFile)
(defnative Pointer LLVMGetNamedGlobal)
(defnative Pointer LLVMGetNamedFunction)
(defnative Integer LLVMSetLinkage)
(defnative Integer LLVMGetIntTypeWidth)
(defnative Pointer LLVMBuildStructGEP)
(defnative Pointer LLVMBuildAdd)
(defnative Pointer LLVMBuildFAdd)
(defnative Pointer LLVMBuildFSub)
(defnative Pointer LLVMBuildMul)
(defnative Pointer LLVMBuildFMul)
(defnative Pointer LLVMBuildFDiv)
(defnative Pointer LLVMBuildSub)
(defnative Pointer LLVMBuildShl)
(defnative Pointer LLVMBuildLShr)
(defnative Pointer LLVMBuildAnd)
(defnative Pointer LLVMBuildNot)
(defnative Pointer LLVMBuildZExt)
(defnative Pointer LLVMBuildTrunc)
(defnative Pointer LLVMBuildFPToSI)
(defnative Pointer LLVMBuildSIToFP)
(defnative Pointer LLVMBuildOr)
(defnative Pointer LLVMBuildMalloc)
(defnative Pointer LLVMSizeOf)
(defnative Pointer LLVMConstNull)
(defnative Pointer LLVMBuildBinOp)
(defnative Pointer LLVMBuildAtomicRMW)
(defnative Pointer LLVMBuildExtractElement)
(defnative Pointer LLVMBuildInsertElement)
(defnative Pointer LLVMBuildGlobalString)
(defnative Pointer LLVMBuildGlobalStringPtr)


(let [module (ModuleCreateWithName "top")
      builder (CreateBuilder)
      main-type (FunctionType (VoidType) nil 0 false)
      main-func (AddFunction module "main" main-type)
      basic-block (AppendBasicBlock main-func "entrypoint")]
  (PositionBuilderAtEnd builder basic-block)
  (let [helloworld (BuildGlobalStringPtr builder "Hello World!\n" "")
        printf-type (FunctionType (Int32Type) (into-array [(PointerType (Int8Type) 0)]) 1 false)
        printf-func (AddFunction module "printf" printf-type)]
    (BuildCall builder printf-func (into-array [helloworld]) 1 "")
    (BuildRetVoid builder))
  (DumpModule module))
